# Generated by Django 5.0.6 on 2024-06-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("store", "0003_rename_price_product_unit_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="collection",
            options={"ordering": ["title"]},
        ),
        migrations.AlterModelOptions(
            name="customer",
            options={"ordering": ["first_name", "last_name"]},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["id"]},
        ),
    ]
